# Generated by Django 3.2.11 on 2022-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.TextField(default='Project1'),
        ),
    ]
