# Generated by Django 4.0.1 on 2022-01-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=120, verbose_name='e.g. user')),
                ('desire', models.CharField(max_length=120, verbose_name='e.g. feature')),
                ('reason', models.CharField(max_length=120, verbose_name='e.g. reason')),
            ],
        ),
        migrations.RenameField(
            model_name='myclubuser',
            old_name='bio',
            new_name='role',
        ),
    ]
