# Generated by Django 4.0.1 on 2022-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_userstory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='first',
            field=models.TextField(default='As'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='second',
            field=models.TextField(default='I would like to'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='third',
            field=models.TextField(default='so that I can'),
        ),
    ]
