# Generated by Django 3.2.11 on 2022-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20220121_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberofus',
            field=models.IntegerField(blank=True, null=True, verbose_name='numberofus'),
        ),
    ]
